/* File: xcmain_guimodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Jul 10 10:34:03 2014
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *xcmain_gui_error;
static PyObject *xcmain_gui_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = xcmain_gui_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = xcmain_gui_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(XCMAIN_GUI,XCMAIN_GUI)(int*,int*,int*,int*,int*,int*,char*,int*,int*,int*,int*,int*,char*,int*,int*,double*,double*,char*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* XCMAIN_GUI *********************************/
static char doc_f2py_rout_xcmain_gui_XCMAIN_GUI[] = "\
XCMAIN_GUI(IDUM,N10,NX0,NY0,IACTION,SORDIR,AEKNOWN,N1LMAG,N2LMAG,N4LMAG,NXLMAG,NYLMAG,WRTIMG,MAG,MINMAG,RES,AZINC,FASTINJ,RET)\n\nWrapper for ``XCMAIN_GUI``.\
\n\nParameters\n----------\n"
"IDUM : input int\n"
"N10 : input int\n"
"NX0 : input int\n"
"NY0 : input int\n"
"IACTION : input int\n"
"SORDIR : input int\n"
"AEKNOWN : input int\n"
"N1LMAG : input int\n"
"N2LMAG : input int\n"
"N4LMAG : input int\n"
"NXLMAG : input int\n"
"NYLMAG : input int\n"
"WRTIMG : input int\n"
"MAG : input int\n"
"MINMAG : input int\n"
"RES : input float\n"
"AZINC : input float\n"
"FASTINJ : input int\n"
"RET : input int";
/* extern void F_FUNC_US(XCMAIN_GUI,XCMAIN_GUI)(int*,int*,int*,int*,int*,int*,char*,int*,int*,int*,int*,int*,char*,int*,int*,double*,double*,char*,int*); */
static PyObject *f2py_rout_xcmain_gui_XCMAIN_GUI(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,char*,int*,int*,int*,int*,int*,char*,int*,int*,double*,double*,char*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int IDUM = 0;
  PyObject *IDUM_capi = Py_None;
  int N10 = 0;
  PyObject *N10_capi = Py_None;
  int NX0 = 0;
  PyObject *NX0_capi = Py_None;
  int NY0 = 0;
  PyObject *NY0_capi = Py_None;
  int IACTION = 0;
  PyObject *IACTION_capi = Py_None;
  int SORDIR = 0;
  PyObject *SORDIR_capi = Py_None;
  char AEKNOWN = 0;
  PyObject *AEKNOWN_capi = Py_None;
  int N1LMAG = 0;
  PyObject *N1LMAG_capi = Py_None;
  int N2LMAG = 0;
  PyObject *N2LMAG_capi = Py_None;
  int N4LMAG = 0;
  PyObject *N4LMAG_capi = Py_None;
  int NXLMAG = 0;
  PyObject *NXLMAG_capi = Py_None;
  int NYLMAG = 0;
  PyObject *NYLMAG_capi = Py_None;
  char WRTIMG = 0;
  PyObject *WRTIMG_capi = Py_None;
  int MAG = 0;
  PyObject *MAG_capi = Py_None;
  int MINMAG = 0;
  PyObject *MINMAG_capi = Py_None;
  double RES = 0;
  PyObject *RES_capi = Py_None;
  double AZINC = 0;
  PyObject *AZINC_capi = Py_None;
  char FASTINJ = 0;
  PyObject *FASTINJ_capi = Py_None;
  int RET = 0;
  PyObject *RET_capi = Py_None;
  static char *capi_kwlist[] = {"IDUM","N10","NX0","NY0","IACTION","SORDIR","AEKNOWN","N1LMAG","N2LMAG","N4LMAG","NXLMAG","NYLMAG","WRTIMG","MAG","MINMAG","RES","AZINC","FASTINJ","RET",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOO:xcmain_gui.XCMAIN_GUI",\
    capi_kwlist,&IDUM_capi,&N10_capi,&NX0_capi,&NY0_capi,&IACTION_capi,&SORDIR_capi,&AEKNOWN_capi,&N1LMAG_capi,&N2LMAG_capi,&N4LMAG_capi,&NXLMAG_capi,&NYLMAG_capi,&WRTIMG_capi,&MAG_capi,&MINMAG_capi,&RES_capi,&AZINC_capi,&FASTINJ_capi,&RET_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable RES */
    f2py_success = double_from_pyobj(&RES,RES_capi,"xcmain_gui.XCMAIN_GUI() 16th argument (RES) can't be converted to double");
  if (f2py_success) {
  /* Processing variable SORDIR */
    f2py_success = int_from_pyobj(&SORDIR,SORDIR_capi,"xcmain_gui.XCMAIN_GUI() 6th argument (SORDIR) can't be converted to int");
  if (f2py_success) {
  /* Processing variable RET */
    f2py_success = int_from_pyobj(&RET,RET_capi,"xcmain_gui.XCMAIN_GUI() 19th argument (RET) can't be converted to int");
  if (f2py_success) {
  /* Processing variable NX0 */
    f2py_success = int_from_pyobj(&NX0,NX0_capi,"xcmain_gui.XCMAIN_GUI() 3rd argument (NX0) can't be converted to int");
  if (f2py_success) {
  /* Processing variable MINMAG */
    f2py_success = int_from_pyobj(&MINMAG,MINMAG_capi,"xcmain_gui.XCMAIN_GUI() 15th argument (MINMAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable N2LMAG */
    f2py_success = int_from_pyobj(&N2LMAG,N2LMAG_capi,"xcmain_gui.XCMAIN_GUI() 9th argument (N2LMAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable NY0 */
    f2py_success = int_from_pyobj(&NY0,NY0_capi,"xcmain_gui.XCMAIN_GUI() 4th argument (NY0) can't be converted to int");
  if (f2py_success) {
  /* Processing variable N1LMAG */
    f2py_success = int_from_pyobj(&N1LMAG,N1LMAG_capi,"xcmain_gui.XCMAIN_GUI() 8th argument (N1LMAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable MAG */
    f2py_success = int_from_pyobj(&MAG,MAG_capi,"xcmain_gui.XCMAIN_GUI() 14th argument (MAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable NYLMAG */
    f2py_success = int_from_pyobj(&NYLMAG,NYLMAG_capi,"xcmain_gui.XCMAIN_GUI() 12nd argument (NYLMAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable N4LMAG */
    f2py_success = int_from_pyobj(&N4LMAG,N4LMAG_capi,"xcmain_gui.XCMAIN_GUI() 10th argument (N4LMAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable FASTINJ */
    FASTINJ = (char)PyObject_IsTrue(FASTINJ_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable NXLMAG */
    f2py_success = int_from_pyobj(&NXLMAG,NXLMAG_capi,"xcmain_gui.XCMAIN_GUI() 11st argument (NXLMAG) can't be converted to int");
  if (f2py_success) {
  /* Processing variable AZINC */
    f2py_success = double_from_pyobj(&AZINC,AZINC_capi,"xcmain_gui.XCMAIN_GUI() 17th argument (AZINC) can't be converted to double");
  if (f2py_success) {
  /* Processing variable IACTION */
    f2py_success = int_from_pyobj(&IACTION,IACTION_capi,"xcmain_gui.XCMAIN_GUI() 5th argument (IACTION) can't be converted to int");
  if (f2py_success) {
  /* Processing variable AEKNOWN */
    AEKNOWN = (char)PyObject_IsTrue(AEKNOWN_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable IDUM */
    f2py_success = int_from_pyobj(&IDUM,IDUM_capi,"xcmain_gui.XCMAIN_GUI() 1st argument (IDUM) can't be converted to int");
  if (f2py_success) {
  /* Processing variable N10 */
    f2py_success = int_from_pyobj(&N10,N10_capi,"xcmain_gui.XCMAIN_GUI() 2nd argument (N10) can't be converted to int");
  if (f2py_success) {
  /* Processing variable WRTIMG */
    WRTIMG = (char)PyObject_IsTrue(WRTIMG_capi);
    f2py_success = 1;
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&IDUM,&N10,&NX0,&NY0,&IACTION,&SORDIR,&AEKNOWN,&N1LMAG,&N2LMAG,&N4LMAG,&NXLMAG,&NYLMAG,&WRTIMG,&MAG,&MINMAG,&RES,&AZINC,&FASTINJ,&RET);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of WRTIMG*/
  /* End of cleaning variable WRTIMG */
  } /*if (f2py_success) of N10*/
  /* End of cleaning variable N10 */
  } /*if (f2py_success) of IDUM*/
  /* End of cleaning variable IDUM */
  } /*if (f2py_success) of AEKNOWN*/
  /* End of cleaning variable AEKNOWN */
  } /*if (f2py_success) of IACTION*/
  /* End of cleaning variable IACTION */
  } /*if (f2py_success) of AZINC*/
  /* End of cleaning variable AZINC */
  } /*if (f2py_success) of NXLMAG*/
  /* End of cleaning variable NXLMAG */
  } /*if (f2py_success) of FASTINJ*/
  /* End of cleaning variable FASTINJ */
  } /*if (f2py_success) of N4LMAG*/
  /* End of cleaning variable N4LMAG */
  } /*if (f2py_success) of NYLMAG*/
  /* End of cleaning variable NYLMAG */
  } /*if (f2py_success) of MAG*/
  /* End of cleaning variable MAG */
  } /*if (f2py_success) of N1LMAG*/
  /* End of cleaning variable N1LMAG */
  } /*if (f2py_success) of NY0*/
  /* End of cleaning variable NY0 */
  } /*if (f2py_success) of N2LMAG*/
  /* End of cleaning variable N2LMAG */
  } /*if (f2py_success) of MINMAG*/
  /* End of cleaning variable MINMAG */
  } /*if (f2py_success) of NX0*/
  /* End of cleaning variable NX0 */
  } /*if (f2py_success) of RET*/
  /* End of cleaning variable RET */
  } /*if (f2py_success) of SORDIR*/
  /* End of cleaning variable SORDIR */
  } /*if (f2py_success) of RES*/
  /* End of cleaning variable RES */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of XCMAIN_GUI *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_CHECK_def[] = {
  {"NX1",0,{{-1}},NPY_INT},
  {"NY1",0,{{-1}},NPY_INT},
  {"ICHECK",0,{{-1}},NPY_INT},
  {"JCHECK",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_CHECK(char *NX1,char *NY1,char *ICHECK,char *JCHECK) {
  int i_f2py=0;
  f2py_CHECK_def[i_f2py++].data = NX1;
  f2py_CHECK_def[i_f2py++].data = NY1;
  f2py_CHECK_def[i_f2py++].data = ICHECK;
  f2py_CHECK_def[i_f2py++].data = JCHECK;
}
extern void F_FUNC(f2pyinitcheck,F2PYINITCHECK)(void(*)(char*,char*,char*,char*));
static void f2py_init_CHECK(void) {
  F_FUNC(f2pyinitcheck,F2PYINITCHECK)(f2py_setup_CHECK);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"XCMAIN_GUI",-1,{{-1}},0,(char *)F_FUNC_US(XCMAIN_GUI,XCMAIN_GUI),(f2py_init_func)f2py_rout_xcmain_gui_XCMAIN_GUI,doc_f2py_rout_xcmain_gui_XCMAIN_GUI},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "xcmain_gui",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_xcmain_gui(void) {
#else
#define RETVAL
PyMODINIT_FUNC initxcmain_gui(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = xcmain_gui_module = PyModule_Create(&moduledef);
#else
  m = xcmain_gui_module = Py_InitModule("xcmain_gui", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module xcmain_gui (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'xcmain_gui' is auto-generated with f2py (version:2).\nFunctions:\n"
"  XCMAIN_GUI(IDUM,N10,NX0,NY0,IACTION,SORDIR,AEKNOWN,N1LMAG,N2LMAG,N4LMAG,NXLMAG,NYLMAG,WRTIMG,MAG,MINMAG,RES,AZINC,FASTINJ,RET)\n"
"COMMON blocks:\n""  /CHECK/ NX1,NY1,ICHECK,JCHECK\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  xcmain_gui_error = PyErr_NewException ("xcmain_gui.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "CHECK", PyFortranObject_New(f2py_CHECK_def,f2py_init_CHECK));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"xcmain_gui");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
