C**************************************************************************
C_TITLE clinom_psnpar.inc
C
C_DESC  Common block hiding phase angle for PSNEG, DPSNEG
C
C_HIST  Feb 28 1989 Randolph Kirk, USGS Flagstaff, Original Version
C**************************************************************************
      COMMON /PSNPAR/ PHASE

      REAL*4 PHASE(2)		! Phase angle(s)
C**************************************************************************
