C**************************************************************************
C_TITLE clinom_trig.inc
C
C_DESC  Common block for performing trig functions
C
C_HIST  May 10 2001 Janet Barrett, USGS Flagstaff, Original Version
C**************************************************************************
      REAL*8 RAD_TO_DEG,DEG_TO_RAD
      DATA RAD_TO_DEG/57.29577951308232087665D0/
      DATA DEG_TO_RAD/.01745329251994329576913D0/
C**************************************************************************
