C**************************************************************************
C_TITLE clinom_msg.inc
C
C_DESC  Common block with parameters controlling message handling in
C       pc2d
C
C_HIST  Jun 01 2001 Janet Barrett, USGS Flagstaff, Original Version
C**************************************************************************
      COMMON /MSG/ PCPMSG

      CHARACTER PCPMSG*512	! Used to send messages to a dialog window
C**************************************************************************
